namespace CannedNet.Models;

public enum GiftContext
	{
		None = -1,
		Default,
		First_Activity,
		Game_Drop,
		All_Daily_Challenges_Complete,
		All_Weekly_Challenge_Complete,
		Daily_Challenge_Complete,
		Weekly_Challenge_Complete,
		Unassigned_Equipment = 10,
		Unassigned_Avatar,
		Unassigned_Consumable,
		Reacquisition = 20,
		Membership,
		NUX_TokensAndDressUp = 30,
		NUX_Experiment1,
		NUX_Experiment2,
		NUX_Experiment3,
		NUX_Experiment4,
		NUX_Experiment5,
		LevelUp = 100,
		Purchased_Gift_A = 500,
		Purchased_Gift_B,
		Purchased_Gift_C,
		Purchased_Gift_D,
		Holiday = 1000,
		Contest,
		Promotion,
		SubscribersOnly,
		Deprecated = 1100,
		RecRoyale = 1200,
		Paintball_ClearCut = 2000,
		Paintball_Homestead,
		Paintball_Quarry,
		Paintball_River,
		Paintball_Dam,
		Paintball_DriveIn,
		Discgolf_Propulsion = 3000,
		Discgolf_Lake,
		Discgolf_Mode_CoopCatch = 3500,
		Quest_Goblin_A = 4000,
		Quest_Goblin_B,
		Quest_Goblin_C,
		Quest_Goblin_S,
		Quest_Goblin_Consumable,
		Quest_Cauldron_A = 4010,
		Quest_Cauldron_B,
		Quest_Cauldron_C,
		Quest_Cauldron_S,
		Quest_Cauldron_Consumable,
		Quest_Pirate1_A = 4100,
		Quest_Pirate1_B,
		Quest_Pirate1_C,
		Quest_Pirate1_S,
		Quest_Pirate1_X,
		Quest_Pirate1_Consumable,
		Quest_Dracula1_A = 4200,
		Quest_Dracula1_B,
		Quest_Dracula1_C,
		Quest_Dracula1_S,
		Quest_Dracula1_X,
		Quest_Dracula1_Consumable,
		Quest_Dracula1_SS,
		Quest_SciFi_A = 4500,
		Quest_SciFi_B,
		Quest_SciFi_C,
		Quest_SciFi_S,
		Quest_Scifi_Consumable,
		Charades = 5000,
		Soccer = 6000,
		Paddleball = 7000,
		Dodgeball = 8000,
		Lasertag = 9000,
		Bowling = 10000,
		StuntRunner_TheMainEvent_A = 11000,
		StuntRunner_TheMainEvent_B,
		StuntRunner_TheMainEvent_C,
		StuntRunner_TheMainEvent_D,
		StuntRunner_TheMainEvent_S,
		StuntRunner_TheMainEvent_X,
		StuntRunner_TheMainEvent_Consumable,
		StuntRunner_TheMainEvent_SS,
		Store_LaserTag = 100000,
		Store_RecCenter = 100010,
		Consumable = 110000,
		Token = 110100,
		Punchcard_Challenge_Complete = 110200,
		All_Punchcard_Challenges_Complete,
		Commerce_Purchase = 200000
	}