// <auto-generated />
using System;
using CannedNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CannedNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403164448_AddRoomInstances")]
    partial class AddRoomInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CannedNet.Account", b =>
                {
                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "displayName");

                    b.Property<int?>("IdentityFlags")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "identityFlags");

                    b.Property<bool>("IsJunior")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isJunior");

                    b.Property<int?>("PersonalPronouns")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "personalPronouns");

                    b.Property<int?>("Platforms")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profileImage");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CannedNet.AvatarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemType");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "friendlyName");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformMask")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platformMask");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rarity");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tooltip");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("avatar_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.CachedLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "lastLoginTime");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("PlatformID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "platformId");

                    b.Property<bool>("RequirePassword")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "requirePassword");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "PlatformID")
                        .IsUnique();

                    b.ToTable("cached_logins", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OutfitSelections");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "SkinColor");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("player_avatars", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerProgression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "playerId");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "xp");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_progressions", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "key");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "playerId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Key")
                        .IsUnique();

                    b.ToTable("player_settings", (string)null);
                });

            modelBuilder.Entity("CannedNet.RoomInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EncryptVoiceChat")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "EncryptVoiceChat");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("clubId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "clubId");

                    b.Property<string>("dataBlob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "dataBlob");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "eventId");

                    b.Property<bool>("isFull")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isFull");

                    b.Property<bool>("isInProgress")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isInProgress");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isPrivate");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "maxCapacity");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("photonRegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "photonRegionId");

                    b.Property<string>("photonRoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "photonRoomId");

                    b.Property<string>("roomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "roomCode");

                    b.Property<int>("roomId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomId");

                    b.Property<int>("roomInstanceId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomInstanceId");

                    b.Property<int>("roomInstanceType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomInstanceType");

                    b.Property<int>("subRoomId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "subRoomId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("room_instances", (string)null);
                });

            modelBuilder.Entity("CannedNet.SavedOutfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OutfitSelections");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewImageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "PreviewImageName");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "SkinColor");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Slot");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("saved_outfits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
