namespace CannedNet;

public enum PushNotificationId
{
    RelationshipChanged = 1,
    MessageReceived = 2,
    MessageDeleted = 3,
    PresenceHeartbeatResponse = 4,
    RefreshLogin = 5,
    Logout = 6,
    SubscriptionUpdateProfile = 11,
    SubscriptionUpdatePresence = 12,
    SubscriptionUpdateGameSession = 13,
    SubscriptionUpdateRoom = 15,
    ModerationQuitGame = 20,
    ModerationUpdateRequired = 21,
    ModerationKick = 22,
    ModerationKickAttemptFailed = 23,
    ModerationRoomBan = 24,
    ServerMaintenance = 25,
    GiftPackageReceived = 30,
    GiftPackageReceivedImmediate = 31,
    ProfileJuniorStatusUpdate = 40,
    RelationshipsInvalid = 50,
    StorefrontBalanceAdd = 60,
    StorefrontBalanceUpdate = 61,
    StorefrontBalancePurchase = 62,
    ConsumableMappingAdded = 70,
    ConsumableMappingRemoved = 71,
    PlayerEventCreated = 80,
    PlayerEventUpdated = 81,
    PlayerEventDeleted = 82,
    PlayerEventResponseChanged = 83,
    PlayerEventResponseDeleted = 84,
    PlayerEventStateChanged = 85,
    ChatMessageReceived = 90,
    CommunityBoardUpdate = 95,
    CommunityBoardAnnouncementUpdate = 96,
    InventionModerationStateChanged = 100
}
